name: "Podcast Generator"
author: "Sai manvith"
description: "Generates a feed for podcast"

inputs:
  email:
    description: "The committer's email"
    required: false
    default: "github-actions@github.com"

  committer_name:
    description: "The committer's name"
    required: false
    default: "github-actions"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "git-branch"
  color: "red"